// Mock Data for DQAI_5 Alumni Platform

// User Profile (mock current user for testing)
const mockCurrentUser = {
    name: "You",
    skills: ["AI", "Machine Learning", "Python", "JavaScript", "React"],
    interests: ["AI", "Mentorship", "Startups", "Technology"],
    graduationYear: 2020,
    department: "Computer Science"
};

// Alumni Data - Updated to match directory photos
const alumniData = [
    {
        id: 1,
        name: "Rajesh Kumar",
        jobTitle: "Senior AI Engineer",
        company: "Google",
        location: "Bangalore, India",
        department: "Computer Science",
        graduationYear: 2015,
        interests: ["AI", "Machine Learning", "Deep Learning", "Computer Vision"],
        skills: ["Python", "TensorFlow", "AI", "Machine Learning", "Computer Vision"],
        email: "rajesh.kumar@google.com",
        profileCompletion: 95,
        lastLogin: new Date('2024-09-15').getTime(),
        pastEventCount: 8,
        pastDonations: 25000,
        activityLevel: "high",
        availableForMentoring: true
    },
    {
        id: 2,
        name: "Priya Sharma",
        jobTitle: "Product Manager",
        company: "Microsoft",
        location: "Seattle, USA",
        department: "Computer Science",
        graduationYear: 2017,
        interests: ["Product Strategy", "AI", "Leadership", "Innovation"],
        skills: ["Product Management", "Strategy", "AI", "Leadership", "Analytics"],
        email: "priya.sharma@microsoft.com",
        profileCompletion: 88,
        lastLogin: new Date('2024-09-16').getTime(),
        pastEventCount: 12,
        pastDonations: 50000,
        activityLevel: "high",
        availableForMentoring: true
    },
    {
        id: 3,
        name: "Arjun Patel",
        jobTitle: "Data Scientist",
        company: "Netflix",
        location: "Mumbai, India",
        department: "Data Science",
        graduationYear: 2019,
        interests: ["Data Science", "Analytics", "Machine Learning", "Statistics"],
        skills: ["Python", "R", "SQL", "Machine Learning", "Statistics"],
        email: "arjun.patel@netflix.com",
        profileCompletion: 92,
        lastLogin: new Date('2024-09-14').getTime(),
        pastEventCount: 6,
        pastDonations: 15000,
        activityLevel: "medium",
        availableForMentoring: false
    },
    {
        id: 4,
        name: "Sneha Reddy",
        jobTitle: "UX Designer",
        company: "Adobe",
        location: "Pune, India",
        department: "Design",
        graduationYear: 2016,
        interests: ["UX Design", "UI Design", "Design Systems", "User Research"],
        skills: ["Figma", "Sketch", "Adobe XD", "User Research", "Prototyping"],
        email: "sneha.reddy@adobe.com",
        profileCompletion: 78,
        lastLogin: new Date('2024-09-13').getTime(),
        pastEventCount: 4,
        pastDonations: 5000,
        activityLevel: "medium",
        availableForMentoring: true
    },
    {
        id: 5,
        name: "Vikram Singh",
        jobTitle: "Software Architect",
        company: "Amazon",
        location: "Hyderabad, India",
        department: "Computer Science",
        graduationYear: 2014,
        interests: ["Architecture", "Software Design", "Cloud Computing", "Scalability"],
        skills: ["Java", "AWS", "Microservices", "System Design", "Leadership"],
        email: "vikram.singh@amazon.com",
        profileCompletion: 98,
        lastLogin: new Date('2024-09-16').getTime(),
        pastEventCount: 15,
        pastDonations: 100000,
        activityLevel: "high",
        availableForMentoring: true
    },
    {
        id: 6,
        name: "Kavya Nair",
        jobTitle: "Research Scientist",
        company: "OpenAI",
        location: "San Francisco, USA",
        department: "AI/ML",
        graduationYear: 2018,
        interests: ["AI Research", "Machine Learning", "NLP", "Deep Learning"],
        skills: ["Python", "PyTorch", "Research", "NLP", "AI"],
        email: "kavya.nair@openai.com",
        profileCompletion: 65,
        lastLogin: new Date('2024-09-10').getTime(),
        pastEventCount: 2,
        pastDonations: 0,
        activityLevel: "low",
        availableForMentoring: false
    },
    {
        id: 7,
        name: "Karthik Iyer",
        jobTitle: "DevOps Engineer",
        company: "Paytm",
        location: "Bangalore",
        department: "Information Technology",
        graduationYear: 2018,
        interests: ["Cloud", "Docker", "Kubernetes", "Automation"],
        skills: ["AWS", "Docker", "Kubernetes", "Python", "DevOps"],
        email: "karthik.iyer@paytm.com",
        profileCompletion: 82,
        lastLogin: new Date('2024-09-12').getTime(),
        pastEventCount: 7,
        pastDonations: 12000,
        activityLevel: "medium"
    },
    {
        id: 8,
        name: "Meera Joshi",
        jobTitle: "AI Researcher",
        company: "IBM Research",
        location: "Pune",
        department: "Computer Science",
        graduationYear: 2015,
        interests: ["Research", "AI", "Robotics", "Computer Vision"],
        skills: ["Python", "AI", "Research", "Computer Vision", "Robotics"],
        email: "meera.joshi@ibm.com",
        profileCompletion: 91,
        lastLogin: new Date('2024-09-15').getTime(),
        pastEventCount: 10,
        pastDonations: 35000,
        activityLevel: "high"
    },
    {
        id: 9,
        name: "Ravi Kumar",
        jobTitle: "Full Stack Developer",
        company: "Swiggy",
        location: "Bangalore",
        department: "Computer Science",
        graduationYear: 2019,
        interests: ["Web Development", "JavaScript", "Python", "Mobile Apps"],
        skills: ["JavaScript", "Python", "React", "Django", "Mobile Development"],
        email: "ravi.kumar@swiggy.com",
        profileCompletion: 75,
        lastLogin: new Date('2024-09-11').getTime(),
        pastEventCount: 5,
        pastDonations: 8000,
        activityLevel: "medium"
    },
    {
        id: 10,
        name: "Kavya Menon",
        jobTitle: "Data Analyst",
        company: "Ola",
        location: "Chennai",
        department: "Statistics",
        graduationYear: 2020,
        interests: ["Data Analysis", "Visualization", "Business Intelligence"],
        skills: ["SQL", "Python", "Tableau", "Excel", "Analytics"],
        email: "kavya.menon@ola.com",
        profileCompletion: 69,
        lastLogin: new Date('2024-09-09').getTime(),
        pastEventCount: 3,
        pastDonations: 3000,
        activityLevel: "low"
    },
    {
        id: 11,
        name: "Suresh Nair",
        jobTitle: "Senior Software Architect",
        company: "Infosys",
        location: "Bangalore",
        department: "Computer Science",
        graduationYear: 2012,
        interests: ["Architecture", "Microservices", "Leadership", "Mentoring"],
        skills: ["Java", "Spring", "Microservices", "Architecture", "Leadership"],
        email: "suresh.nair@infosys.com",
        profileCompletion: 94,
        lastLogin: new Date('2024-09-14').getTime(),
        pastEventCount: 18,
        pastDonations: 75000,
        activityLevel: "high"
    },
    {
        id: 12,
        name: "Deepika Agarwal",
        jobTitle: "UX Designer",
        company: "Adobe",
        location: "Noida",
        department: "Design",
        graduationYear: 2018,
        interests: ["Design", "User Experience", "Psychology", "Research"],
        skills: ["Design", "Figma", "Research", "Psychology", "Prototyping"],
        email: "deepika.agarwal@adobe.com",
        profileCompletion: 87,
        lastLogin: new Date('2024-09-13').getTime(),
        pastEventCount: 9,
        pastDonations: 20000,
        activityLevel: "medium"
    },
    {
        id: 13,
        name: "Arun Krishnan",
        jobTitle: "Blockchain Developer",
        company: "Coinbase",
        location: "Kochi",
        department: "Computer Science",
        graduationYear: 2017,
        interests: ["Blockchain", "Cryptocurrency", "Solidity", "DeFi"],
        skills: ["Blockchain", "Solidity", "Web3", "JavaScript", "Cryptography"],
        email: "arun.krishnan@coinbase.com",
        profileCompletion: 83,
        lastLogin: new Date('2024-09-12').getTime(),
        pastEventCount: 6,
        pastDonations: 18000,
        activityLevel: "medium"
    },
    {
        id: 14,
        name: "Nisha Verma",
        jobTitle: "Mobile App Developer",
        company: "Paytm",
        location: "Gurgaon",
        department: "Computer Science",
        graduationYear: 2019,
        interests: ["Mobile Development", "Flutter", "iOS", "Android"],
        skills: ["Flutter", "iOS", "Android", "Dart", "Swift"],
        email: "nisha.verma@paytm.com",
        profileCompletion: 76,
        lastLogin: new Date('2024-09-10').getTime(),
        pastEventCount: 4,
        pastDonations: 6000,
        activityLevel: "low"
    },
    {
        id: 15,
        name: "Rajesh Pillai",
        jobTitle: "Security Engineer",
        company: "Razorpay",
        location: "Bangalore",
        department: "Cybersecurity",
        graduationYear: 2016,
        interests: ["Cybersecurity", "Penetration Testing", "Security Audits"],
        skills: ["Security", "Penetration Testing", "Python", "Networking"],
        email: "rajesh.pillai@razorpay.com",
        profileCompletion: 90,
        lastLogin: new Date('2024-09-15').getTime(),
        pastEventCount: 11,
        pastDonations: 28000,
        activityLevel: "high"
    },
    // Adding 15 more alumni to reach 30 total
    {
        id: 16,
        name: "Pooja Bansal",
        jobTitle: "Business Analyst",
        company: "McKinsey",
        location: "Mumbai",
        department: "Business Administration",
        graduationYear: 2017,
        interests: ["Strategy", "Consulting", "Analytics", "Business"],
        skills: ["Analytics", "Strategy", "Consulting", "Excel", "PowerBI"],
        email: "pooja.bansal@mckinsey.com",
        profileCompletion: 85,
        lastLogin: new Date('2024-09-14').getTime(),
        pastEventCount: 7,
        pastDonations: 22000,
        activityLevel: "medium"
    },
    {
        id: 17,
        name: "Sanjay Rao",
        jobTitle: "Cloud Solutions Architect",
        company: "AWS",
        location: "Hyderabad",
        department: "Computer Science",
        graduationYear: 2014,
        interests: ["Cloud", "AWS", "Architecture", "Serverless"],
        skills: ["AWS", "Cloud", "Serverless", "Python", "Architecture"],
        email: "sanjay.rao@aws.com",
        profileCompletion: 96,
        lastLogin: new Date('2024-09-16').getTime(),
        pastEventCount: 14,
        pastDonations: 60000,
        activityLevel: "high"
    },
    {
        id: 18,
        name: "Lakshmi Narayanan",
        jobTitle: "Quality Assurance Engineer",
        company: "Thoughtworks",
        location: "Chennai",
        department: "Computer Science",
        graduationYear: 2018,
        interests: ["Testing", "Automation", "Quality", "Agile"],
        skills: ["Testing", "Selenium", "Automation", "Java", "Agile"],
        email: "lakshmi.narayanan@thoughtworks.com",
        profileCompletion: 73,
        lastLogin: new Date('2024-09-11').getTime(),
        pastEventCount: 5,
        pastDonations: 9000,
        activityLevel: "medium"
    },
    {
        id: 19,
        name: "Amit Agarwal",
        jobTitle: "Startup Founder",
        company: "TechStart",
        location: "Bangalore",
        department: "Computer Science",
        graduationYear: 2015,
        interests: ["Entrepreneurship", "Startups", "Innovation", "Leadership"],
        skills: ["Leadership", "Strategy", "Product", "Fundraising", "Innovation"],
        email: "amit.agarwal@techstart.com",
        profileCompletion: 92,
        lastLogin: new Date('2024-09-15').getTime(),
        pastEventCount: 16,
        pastDonations: 40000,
        activityLevel: "high"
    },
    {
        id: 20,
        name: "Shweta Kulkarni",
        jobTitle: "Data Engineer",
        company: "Netflix",
        location: "Mumbai",
        department: "Computer Science",
        graduationYear: 2018,
        interests: ["Big Data", "ETL", "Data Pipelines", "Analytics"],
        skills: ["Spark", "Hadoop", "Python", "SQL", "Kafka"],
        email: "shweta.kulkarni@netflix.com",
        profileCompletion: 88,
        lastLogin: new Date('2024-09-13').getTime(),
        pastEventCount: 8,
        pastDonations: 16000,
        activityLevel: "medium"
    },
    {
        id: 21,
        name: "Harish Reddy",
        jobTitle: "AI Product Manager",
        company: "Meta",
        location: "Bangalore",
        department: "Computer Science",
        graduationYear: 2016,
        interests: ["AI", "Product", "Strategy", "Innovation"],
        skills: ["Product Management", "AI", "Strategy", "Analytics", "Leadership"],
        email: "harish.reddy@meta.com",
        profileCompletion: 94,
        lastLogin: new Date('2024-09-16').getTime(),
        pastEventCount: 13,
        pastDonations: 45000,
        activityLevel: "high"
    },
    {
        id: 22,
        name: "Ritika Singh",
        jobTitle: "Backend Developer",
        company: "Uber",
        location: "Hyderabad",
        department: "Computer Science",
        graduationYear: 2019,
        interests: ["Backend", "APIs", "Microservices", "Databases"],
        skills: ["Java", "Spring", "Microservices", "PostgreSQL", "APIs"],
        email: "ritika.singh@uber.com",
        profileCompletion: 79,
        lastLogin: new Date('2024-09-12').getTime(),
        pastEventCount: 4,
        pastDonations: 7000,
        activityLevel: "medium"
    },
    {
        id: 23,
        name: "Manish Tiwari",
        jobTitle: "Research Scientist",
        company: "NVIDIA",
        location: "Pune",
        department: "Computer Science",
        graduationYear: 2015,
        interests: ["Research", "GPU Computing", "AI", "HPC"],
        skills: ["CUDA", "AI", "Research", "C++", "GPU Computing"],
        email: "manish.tiwari@nvidia.com",
        profileCompletion: 97,
        lastLogin: new Date('2024-09-15').getTime(),
        pastEventCount: 12,
        pastDonations: 55000,
        activityLevel: "high"
    },
    {
        id: 24,
        name: "Divya Kumari",
        jobTitle: "Frontend Engineer",
        company: "Airbnb",
        location: "Delhi",
        department: "Computer Science",
        graduationYear: 2020,
        interests: ["Frontend", "React", "UI/UX", "Performance"],
        skills: ["React", "JavaScript", "TypeScript", "CSS", "Performance"],
        email: "divya.kumari@airbnb.com",
        profileCompletion: 71,
        lastLogin: new Date('2024-09-10').getTime(),
        pastEventCount: 3,
        pastDonations: 4000,
        activityLevel: "low"
    },
    {
        id: 25,
        name: "Gopal Krishna",
        jobTitle: "Database Administrator",
        company: "Oracle",
        location: "Bangalore",
        department: "Computer Science",
        graduationYear: 2013,
        interests: ["Databases", "Performance", "Administration", "SQL"],
        skills: ["Oracle", "MySQL", "PostgreSQL", "Performance Tuning", "Administration"],
        email: "gopal.krishna@oracle.com",
        profileCompletion: 86,
        lastLogin: new Date('2024-09-13').getTime(),
        pastEventCount: 9,
        pastDonations: 30000,
        activityLevel: "medium"
    },
    {
        id: 26,
        name: "Preeti Agrawal",
        jobTitle: "Machine Learning Engineer",
        company: "Spotify",
        location: "Mumbai",
        department: "Computer Science",
        graduationYear: 2017,
        interests: ["Machine Learning", "Music", "Recommendation Systems", "AI"],
        skills: ["Python", "Machine Learning", "TensorFlow", "Recommendation Systems", "Scala"],
        email: "preeti.agrawal@spotify.com",
        profileCompletion: 93,
        lastLogin: new Date('2024-09-14').getTime(),
        pastEventCount: 10,
        pastDonations: 25000,
        activityLevel: "high"
    },
    {
        id: 27,
        name: "Rohit Jain",
        jobTitle: "Site Reliability Engineer",
        company: "Google",
        location: "Bangalore",
        department: "Computer Science",
        graduationYear: 2018,
        interests: ["SRE", "Monitoring", "Automation", "Reliability"],
        skills: ["SRE", "Kubernetes", "Monitoring", "Python", "Go"],
        email: "rohit.jain@google.com",
        profileCompletion: 89,
        lastLogin: new Date('2024-09-15').getTime(),
        pastEventCount: 11,
        pastDonations: 32000,
        activityLevel: "high"
    },
    {
        id: 28,
        name: "Swati Chopra",
        jobTitle: "Product Designer",
        company: "Figma",
        location: "San Francisco",
        department: "Design",
        graduationYear: 2019,
        interests: ["Design", "Product", "User Research", "Prototyping"],
        skills: ["Design", "Figma", "User Research", "Prototyping", "Design Systems"],
        email: "swati.chopra@figma.com",
        profileCompletion: 91,
        lastLogin: new Date('2024-09-16').getTime(),
        pastEventCount: 8,
        pastDonations: 18000,
        activityLevel: "medium"
    },
    {
        id: 29,
        name: "Vivek Sharma",
        jobTitle: "Technical Lead",
        company: "Salesforce",
        location: "Hyderabad",
        department: "Computer Science",
        graduationYear: 2014,
        interests: ["Leadership", "CRM", "Cloud", "Team Management"],
        skills: ["Leadership", "Salesforce", "Java", "Cloud", "Team Management"],
        email: "vivek.sharma@salesforce.com",
        profileCompletion: 95,
        lastLogin: new Date('2024-09-15').getTime(),
        pastEventCount: 15,
        pastDonations: 42000,
        activityLevel: "high"
    },
    {
        id: 30,
        name: "Neha Gupta",
        jobTitle: "Growth Hacker",
        company: "Razorpay",
        location: "Bangalore",
        department: "Marketing",
        graduationYear: 2020,
        interests: ["Growth", "Marketing", "Analytics", "A/B Testing"],
        skills: ["Growth", "Marketing", "Analytics", "A/B Testing", "Python"],
        email: "neha.gupta@razorpay.com",
        profileCompletion: 77,
        lastLogin: new Date('2024-09-11').getTime(),
        pastEventCount: 5,
        pastDonations: 8000,
        activityLevel: "medium"
    }
];

// Job Data (15 jobs)
const jobsData = [
    {
        id: 1,
        title: "Senior AI Engineer",
        company: "Google",
        location: "Bangalore",
        type: "Full-time",
        tags: ["AI", "Machine Learning", "Python", "TensorFlow", "Deep Learning"],
        description: "Join our AI team to build next-generation intelligent systems.",
        posted: "2 days ago"
    },
    {
        id: 2,
        title: "Full Stack Developer",
        company: "Microsoft",
        location: "Hyderabad",
        type: "Full-time",
        tags: ["JavaScript", "React", "Node.js", "Azure", "Full Stack"],
        description: "Develop scalable web applications using modern technologies.",
        posted: "1 day ago"
    },
    {
        id: 3,
        title: "Data Scientist",
        company: "Amazon",
        location: "Mumbai",
        type: "Full-time",
        tags: ["Python", "Machine Learning", "Statistics", "SQL", "Analytics"],
        description: "Analyze large datasets to drive business insights and decisions.",
        posted: "3 days ago"
    },
    {
        id: 4,
        title: "DevOps Engineer",
        company: "Flipkart",
        location: "Bangalore",
        type: "Full-time",
        tags: ["Docker", "Kubernetes", "AWS", "DevOps", "Automation"],
        description: "Build and maintain scalable infrastructure and deployment pipelines.",
        posted: "1 week ago"
    },
    {
        id: 5,
        title: "Product Manager",
        company: "Zomato",
        location: "Delhi",
        type: "Full-time",
        tags: ["Product Management", "Strategy", "Analytics", "Leadership", "Growth"],
        description: "Lead product development and drive growth initiatives.",
        posted: "4 days ago"
    },
    {
        id: 6,
        title: "Frontend Developer",
        company: "Paytm",
        location: "Bangalore",
        type: "Full-time",
        tags: ["React", "JavaScript", "CSS", "HTML", "Frontend"],
        description: "Create beautiful and responsive user interfaces.",
        posted: "5 days ago"
    },
    {
        id: 7,
        title: "Machine Learning Researcher",
        company: "OpenAI",
        location: "San Francisco",
        type: "Full-time",
        tags: ["Research", "AI", "NLP", "PyTorch", "Deep Learning"],
        description: "Conduct cutting-edge research in artificial intelligence.",
        posted: "1 day ago"
    },
    {
        id: 8,
        title: "Backend Developer",
        company: "Swiggy",
        location: "Bangalore",
        type: "Full-time",
        tags: ["Java", "Spring", "Microservices", "PostgreSQL", "APIs"],
        description: "Design and develop scalable backend systems and APIs.",
        posted: "6 days ago"
    },
    {
        id: 9,
        title: "UX Designer",
        company: "Adobe",
        location: "Noida",
        type: "Full-time",
        tags: ["Design", "UX", "Figma", "User Research", "Prototyping"],
        description: "Design intuitive user experiences for creative software.",
        posted: "2 days ago"
    },
    {
        id: 10,
        title: "Blockchain Developer",
        company: "Coinbase",
        location: "Remote",
        type: "Full-time",
        tags: ["Blockchain", "Solidity", "Web3", "Ethereum", "DeFi"],
        description: "Build decentralized applications and smart contracts.",
        posted: "3 days ago"
    },
    {
        id: 11,
        title: "Mobile App Developer",
        company: "Uber",
        location: "Hyderabad",
        type: "Full-time",
        tags: ["Flutter", "iOS", "Android", "Mobile", "React Native"],
        description: "Develop mobile applications for millions of users.",
        posted: "1 week ago"
    },
    {
        id: 12,
        title: "Security Engineer",
        company: "Razorpay",
        location: "Bangalore",
        type: "Full-time",
        tags: ["Security", "Penetration Testing", "Python", "Cybersecurity"],
        description: "Ensure the security of financial technology systems.",
        posted: "4 days ago"
    },
    {
        id: 13,
        title: "Cloud Solutions Architect",
        company: "AWS",
        location: "Mumbai",
        type: "Full-time",
        tags: ["AWS", "Cloud", "Architecture", "Serverless", "Infrastructure"],
        description: "Design cloud solutions for enterprise customers.",
        posted: "5 days ago"
    },
    {
        id: 14,
        title: "Quality Assurance Engineer",
        company: "Thoughtworks",
        location: "Chennai",
        type: "Full-time",
        tags: ["Testing", "Automation", "Selenium", "QA", "Agile"],
        description: "Ensure software quality through comprehensive testing.",
        posted: "1 week ago"
    },
    {
        id: 15,
        title: "Growth Product Manager",
        company: "Spotify",
        location: "Mumbai",
        type: "Full-time",
        tags: ["Product", "Growth", "Analytics", "A/B Testing", "Strategy"],
        description: "Drive user growth and engagement for music streaming platform.",
        posted: "2 days ago"
    }
];

// Events Data - Updated to match events page photos
const eventsData = [
    {
        id: 1,
        title: "Bangalore Alumni Meetup",
        date: "2025-02-15",
        time: "5:00 PM",
        location: "UB City Mall, Bangalore",
        type: "networking",
        description: "Tech & Career Networking event for Bangalore alumni",
        maxAttendees: 60,
        registeredCount: 47,
        tags: ["networking", "tech", "career"],
        userRegistered: false
    },
    {
        id: 2,
        title: "AI & Machine Learning Workshop",
        date: "2025-02-20",
        time: "2:00 PM",
        location: "Virtual Event",
        type: "workshop",
        description: "Hands-on workshop on latest AI/ML trends and technologies",
        maxAttendees: 200,
        registeredCount: 156,
        tags: ["AI", "Machine Learning", "Workshop"],
        userRegistered: true
    },
    {
        id: 3,
        title: "Annual Alumni Reunion 2024",
        date: "2025-03-10",
        time: "10:00 AM",
        location: "University Campus",
        type: "reunion",
        description: "Annual reunion with all departments, awards ceremony, and celebrations",
        maxAttendees: 500,
        registeredCount: 342,
        tags: ["reunion", "celebration", "awards"],
        userRegistered: false
    },
    {
        id: 4,
        title: "Startup Pitch Night",
        date: "2025-02-25",
        time: "6:30 PM",
        location: "91springboard, Mumbai",
        type: "entrepreneurship",
        description: "Alumni entrepreneurs pitch their startups, networking with investors",
        maxAttendees: 40,
        registeredCount: 23,
        tags: ["startup", "entrepreneurship", "pitch"],
        userRegistered: true
    },
    {
        id: 5,
        title: "Career Transition Panel",
        date: "2025-03-05",
        time: "7:00 PM",
        location: "Virtual Event",
        type: "career",
        description: "Panel discussion on career transitions with senior alumni",
        maxAttendees: 150,
        registeredCount: 89,
        tags: ["career", "transition", "panel"],
        userRegistered: false
    },
    {
        id: 6,
        title: "Annual Fundraising Gala",
        date: "2025-11-20",
        time: "7:00 PM",
        location: "Mumbai",
        type: "Fundraising",
        description: "Annual gala dinner to raise funds for student scholarships",
        capacity: 300,
        registrations: 234,
        tags: ["Fundraising", "Scholarship", "Gala"],
        organizer: "Alumni Association"
    },
    {
        id: 7,
        title: "Tech Talk: Future of Web3",
        date: "2025-10-03",
        time: "3:00 PM",
        location: "Pune",
        type: "Technical",
        description: "Deep dive into blockchain and decentralized technologies",
        capacity: 75,
        registrations: 52,
        tags: ["Blockchain", "Web3", "Technology"],
        organizer: "Blockchain Alumni Group"
    },
    {
        id: 8,
        title: "Alumni Sports Tournament",
        date: "2025-10-22",
        time: "9:00 AM",
        location: "Chennai",
        type: "Sports",
        description: "Multi-sport tournament for alumni and families",
        capacity: 200,
        registrations: 178,
        tags: ["Sports", "Recreation", "Family"],
        organizer: "Sports Alumni Committee"
    },
    {
        id: 9,
        title: "Product Management Masterclass",
        date: "2025-10-05",
        time: "1:00 PM",
        location: "Bangalore",
        type: "Workshop",
        description: "Advanced product management strategies and frameworks",
        capacity: 60,
        registrations: 38,
        tags: ["Product Management", "Strategy", "Professional Development"],
        organizer: "Product Alumni Network"
    },
    {
        id: 10,
        title: "Homecoming Weekend",
        date: "2025-11-15",
        time: "10:00 AM",
        location: "Campus",
        type: "Social",
        description: "Annual homecoming celebration with campus tours and activities",
        capacity: 500,
        registrations: 387,
        tags: ["Homecoming", "Campus", "Tradition"],
        organizer: "Alumni Relations Office"
    },
    {
        id: 11,
        title: "Design Thinking Workshop",
        date: "2025-09-28",
        time: "10:00 AM",
        location: "Bangalore",
        type: "Workshop",
        description: "Hands-on workshop on design thinking methodologies",
        capacity: 50,
        registrations: 42,
        tags: ["Design", "Innovation", "Workshop"],
        organizer: "Design Alumni Group"
    },
    {
        id: 12,
        title: "Investment and Finance Seminar",
        date: "2025-10-18",
        time: "2:00 PM",
        location: "Mumbai",
        type: "Seminar",
        description: "Seminar on investment strategies and financial planning",
        capacity: 100,
        registrations: 71,
        tags: ["Finance", "Investment", "Wealth Management"],
        organizer: "Finance Alumni Chapter"
    },
    {
        id: 13,
        title: "Mentorship Speed Dating",
        date: "2025-10-01",
        time: "5:00 PM",
        location: "Delhi",
        type: "Networking",
        description: "Quick networking sessions to connect mentors and mentees",
        capacity: 80,
        registrations: 63,
        tags: ["Mentorship", "Networking", "Career"],
        organizer: "Mentorship Program"
    },
    {
        id: 14,
        title: "Cultural Heritage Festival",
        date: "2025-10-26",
        time: "6:00 PM",
        location: "Kolkata",
        type: "Cultural",
        description: "Celebration of diverse cultural heritage of our alumni",
        capacity: 250,
        registrations: 189,
        tags: ["Culture", "Heritage", "Diversity"],
        organizer: "Cultural Committee"
    },
    {
        id: 15,
        title: "Healthcare Innovation Summit",
        date: "2025-10-20",
        time: "9:00 AM",
        location: "Hyderabad",
        type: "Technical",
        description: "Summit on latest innovations in healthcare technology",
        capacity: 150,
        registrations: 112,
        tags: ["Healthcare", "Innovation", "Technology"],
        organizer: "Healthcare Alumni Network"
    },
    {
        id: 16,
        title: "Young Alumni Mixer",
        date: "2025-09-22",
        time: "7:00 PM",
        location: "Bangalore",
        type: "Networking",
        description: "Networking event specifically for recent graduates",
        capacity: 120,
        registrations: 95,
        tags: ["Young Alumni", "Networking", "Recent Graduates"],
        organizer: "Young Alumni Committee"
    },
    {
        id: 17,
        title: "Sustainability and Environment Panel",
        date: "2025-10-14",
        time: "3:00 PM",
        location: "Chennai",
        type: "Panel",
        description: "Discussion on sustainability practices in technology",
        capacity: 90,
        registrations: 67,
        tags: ["Sustainability", "Environment", "Technology"],
        organizer: "Green Alumni Initiative"
    },
    {
        id: 18,
        title: "Leadership Excellence Workshop",
        date: "2025-10-07",
        time: "10:00 AM",
        location: "Pune",
        type: "Workshop",
        description: "Workshop on developing leadership skills and executive presence",
        capacity: 70,
        registrations: 51,
        tags: ["Leadership", "Management", "Professional Development"],
        organizer: "Leadership Development Program"
    },
    {
        id: 19,
        title: "Alumni Book Club Meeting",
        date: "2025-09-26",
        time: "4:00 PM",
        location: "Delhi",
        type: "Social",
        description: "Monthly meeting of the alumni book club",
        capacity: 30,
        registrations: 24,
        tags: ["Books", "Literature", "Discussion"],
        organizer: "Literary Alumni Society"
    },
    {
        id: 20,
        title: "Global Alumni Virtual Meetup",
        date: "2025-10-10",
        time: "8:00 PM",
        location: "Virtual",
        type: "Virtual",
        description: "Virtual meetup connecting global alumni across time zones",
        capacity: 500,
        registrations: 298,
        tags: ["Global", "Virtual", "International"],
        organizer: "International Alumni Network"
    }
];

// Feedback Data (20 feedback items)
const feedbackData = [
    {
        id: 1,
        text: "The alumni platform is absolutely fantastic! I love how easy it is to connect with fellow graduates and find relevant job opportunities. The AI recommendations are spot-on!",
        sentiment: "positive",
        score: 0.9,
        author: "Anonymous",
        date: "2024-09-15",
        category: "Platform"
    },
    {
        id: 2,
        text: "Great initiative, but the search function could be improved. Sometimes it takes too long to find specific alumni profiles.",
        sentiment: "neutral",
        score: 0.2,
        author: "Alumni #1234",
        date: "2024-09-14",
        category: "Search"
    },
    {
        id: 3,
        text: "Amazing work on the job recommendations! Found my dream job through this platform. Thank you so much!",
        sentiment: "positive",
        score: 0.95,
        author: "Rahul K.",
        date: "2024-09-13",
        category: "Jobs"
    },
    {
        id: 4,
        text: "The event prediction feature is not very accurate. It suggested I would attend events I have no interest in.",
        sentiment: "negative",
        score: -0.6,
        author: "Anonymous",
        date: "2024-09-12",
        category: "Events"
    },
    {
        id: 5,
        text: "Love the clean interface and user-friendly design. Everything is intuitive and well-organized.",
        sentiment: "positive",
        score: 0.8,
        author: "Priya S.",
        date: "2024-09-11",
        category: "UI/UX"
    },
    {
        id: 6,
        text: "The donation forecasting feature is interesting, but I'm not sure how accurate the predictions are.",
        sentiment: "neutral",
        score: 0.1,
        author: "Anonymous",
        date: "2024-09-10",
        category: "Donations"
    },
    {
        id: 7,
        text: "Excellent platform for networking! Met several interesting people from my batch. Highly recommend!",
        sentiment: "positive",
        score: 0.85,
        author: "Vikram R.",
        date: "2024-09-09",
        category: "Networking"
    },
    {
        id: 8,
        text: "The mobile app is buggy and crashes frequently. Please fix the technical issues.",
        sentiment: "negative",
        score: -0.7,
        author: "Anonymous",
        date: "2024-09-08",
        category: "Technical"
    },
    {
        id: 9,
        text: "Good concept overall, but needs more features for international alumni. Limited functionality for overseas members.",
        sentiment: "neutral",
        score: 0.3,
        author: "Anita M.",
        date: "2024-09-07",
        category: "Features"
    },
    {
        id: 10,
        text: "Outstanding platform! The AI insights are really helpful for making connections. Keep up the great work!",
        sentiment: "positive",
        score: 0.9,
        author: "Karthik I.",
        date: "2024-09-06",
        category: "AI Features"
    },
    {
        id: 11,
        text: "Privacy concerns about how much personal data is being collected and used by the AI systems.",
        sentiment: "negative",
        score: -0.4,
        author: "Anonymous",
        date: "2024-09-05",
        category: "Privacy"
    },
    {
        id: 12,
        text: "The mentorship matching feature is brilliant! Connected with an amazing mentor who's helping me grow professionally.",
        sentiment: "positive",
        score: 0.88,
        author: "Sneha R.",
        date: "2024-09-04",
        category: "Mentorship"
    },
    {
        id: 13,
        text: "Platform is okay but the loading times are quite slow. Could use some performance optimization.",
        sentiment: "neutral",
        score: 0.15,
        author: "Ravi K.",
        date: "2024-09-03",
        category: "Performance"
    },
    {
        id: 14,
        text: "Fantastic job on the alumni directory! Easy to search and filter. Found my college roommate after 10 years!",
        sentiment: "positive",
        score: 0.92,
        author: "Meera J.",
        date: "2024-09-02",
        category: "Alumni Directory"
    },
    {
        id: 15,
        text: "The notification system is annoying. Too many irrelevant notifications throughout the day.",
        sentiment: "negative",
        score: -0.5,
        author: "Anonymous",
        date: "2024-09-01",
        category: "Notifications"
    },
    {
        id: 16,
        text: "Great platform with lots of potential. Hope to see more career development resources added soon.",
        sentiment: "positive",
        score: 0.7,
        author: "Kavya M.",
        date: "2024-08-31",
        category: "Career Development"
    },
    {
        id: 17,
        text: "Login process is too complicated. Should have single sign-on with popular platforms like Google or LinkedIn.",
        sentiment: "neutral",
        score: 0.05,
        author: "Suresh N.",
        date: "2024-08-30",
        category: "Authentication"
    },
    {
        id: 18,
        text: "Amazing platform! The event recommendations are accurate and I've attended several great networking events.",
        sentiment: "positive",
        score: 0.87,
        author: "Deepika A.",
        date: "2024-08-29",
        category: "Events"
    },
    {
        id: 19,
        text: "Dashboard is confusing and cluttered. Needs a cleaner design with better information hierarchy.",
        sentiment: "negative",
        score: -0.3,
        author: "Anonymous",
        date: "2024-08-28",
        category: "Dashboard"
    },
    {
        id: 20,
        text: "Excellent work on the sentiment analysis feature! It's fascinating to see how feedback is processed and categorized.",
        sentiment: "positive",
        score: 0.83,
        author: "Arun K.",
        date: "2024-08-27",
        category: "AI Features"
    }
];

// Department distribution data for charts
const departmentData = {
    "Computer Science": 18,
    "Information Technology": 4,
    "Business Administration": 2,
    "Design": 2,
    "Statistics": 1,
    "Mathematics": 1,
    "Marketing": 1,
    "Cybersecurity": 1
};

// Skills distribution data for charts
const skillsData = {
    "JavaScript": 12,
    "Python": 15,
    "AI": 8,
    "Machine Learning": 9,
    "React": 7,
    "Leadership": 6,
    "Java": 5,
    "Design": 4,
    "AWS": 4,
    "SQL": 3
};